### PR TITLE
Update Requirement.txt and models.py at pep8 standard

### PR DESCRIPTION
**Pull request by imskr**

### CODE REVIEW

**Comment by mohitkh7** [comment]
I am still getting this error on running pycodestyle over `models.py` file
```
models.py:63:1: E101 indentation contains mixed spaces and tabs
models.py:63:1: W191 indentation contains tabs
models.py:64:1: W191 indentation contains tabs
models.py:65:1: W191 indentation contains tabs
models.py:67:1: E101 indentation contains mixed spaces and tabs

```

**Comment by imskr** [comment]
@mohitkh7 review this again!

**Comment by imskr** [comment]
fixed everything!

**Comment by mohitkh7** [comment]
Its working as expected. Good work.
You have created 4 commits. Merge them all into single commit and send PR again.
you can use `git rebase -i HEAD~4` command to do so.

**Comment by imskr** [comment]
I'm sending the fresh PR

**Pull request closed without merging**
